# -*- coding: utf-8 -*-
"""PRODIGY_DS_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-yPOMmWYpBaPKv-OrJLWy4Upsq2-KqT
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('/content/world_population.csv')

data.head()

data.info()

"""Top Ten Most Populated Countries."""

required_columns = ['Country/Territory', '2022 Population']
if not all(column in data.columns for column in required_columns):
    raise ValueError(f"CSV file must contain the columns: {required_columns}")
data['2022 Population'] = pd.to_numeric(data['2022 Population'], errors='coerce')

df = data.dropna(subset=['2022 Population'])
df_sorted = df.sort_values(by='2022 Population', ascending=False)


top_ten_countries = df_sorted.head(10)
print("\nTop Ten Most Populated Countries:")
print(top_ten_countries[['Country/Territory', '2022 Population']])

plt.figure(figsize=(12, 8))
plt.barh(top_ten_countries['Country/Territory'], top_ten_countries['2022 Population'], color='skyblue')
plt.xlabel('2022 Population')
plt.ylabel('Country')
plt.title('Top Ten Most Populated Countries In 2022')
plt.gca().invert_yaxis()
plt.show()

"""Top Ten Countries With Highest growth Rate

"""

df['Growth Rate'] = pd.to_numeric(df['Growth Rate'], errors='coerce')
df = df.dropna(subset=['Growth Rate'])
df_sorted = df.sort_values(by='Growth Rate', ascending=False)


top_ten_countries = df_sorted.head(10)


print("\nTop Ten Countries with the Highest Growth Rates:")
print(top_ten_countries[['Country/Territory', 'Growth Rate']])

plt.figure(figsize=(12, 8))
plt.barh(top_ten_countries['Country/Territory'], top_ten_countries['Growth Rate'], color='skyblue')
plt.xlabel('Growth Rate')
plt.ylabel('Country')
plt.title('Top 10 Countries with the Highest Population Growth Rates')
plt.gca().invert_yaxis()
plt.show()

"""Countries With Least Population"""

required_columns = ['Country/Territory', '2022 Population']
if not all(column in data.columns for column in required_columns):
    raise ValueError(f"CSV file must contain the columns: {required_columns}")
data['2022 Population'] = pd.to_numeric(data['2022 Population'], errors='coerce')

df = data.dropna(subset=['2022 Population'])
df_sorted = df.sort_values(by='2022 Population', ascending=True)


top_ten_countries = df_sorted.head(10)
print("\nTop Ten Least Populated Countries:")
print(top_ten_countries[['Country/Territory', '2022 Population']])

plt.figure(figsize=(12, 8))
plt.barh(top_ten_countries['Country/Territory'], top_ten_countries['2022 Population'], color='skyblue')
plt.xlabel('2022 Population')
plt.ylabel('Country')
plt.title('Top Ten Least Populated Countries In 2022')
plt.gca().invert_yaxis()
plt.show()

"""Population density Of Certain Countries"""

countries = ['China', 'India', 'United States', 'Indonesia', 'Pakistan', 'Brazil']


filtered_df = df[df['Country/Territory'].isin(countries)]
print("Population Density of Selected Countries:")
for country in countries:
    density = filtered_df.loc[filtered_df['Country/Territory'] == country, 'Density (per km²)'].values[0]
    print(f"{country}: {density:.2f} people per square kilometer")

countries = ['China', 'India', 'United States', 'Indonesia', 'Pakistan', 'Brazil']


filtered_df = df[df['Country/Territory'].isin(countries)]

plt.figure(figsize=(10, 8))
plt.pie(filtered_df['Density (per km²)'], labels=filtered_df['Country/Territory'], autopct='%1.1f%%', startangle=140)
plt.title('Population Density of Selected Countries')
plt.axis('equal')
plt.show()